services:
  dev-postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: task_manager
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./testdeta.sql:/docker-entrypoint-initdb.d/testdata.sql
    networks:
      - lesson
networks:
  lesson:
