CREATE TABLE IF NOT EXISTS Account (
    AccountID SERIAL PRIMARY KEY,
    AccountName VARCHAR(255) NOT NULL,
    PathHash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Task (
    TaskID SERIAL PRIMARY KEY,
    AccountID INT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    DueDate TIMESTAMP NOT NULL,
    Progress INT NOT NULL,
    FOREIGN KEY (AccountID) REFERENCES Account(AccountID)
);